# Generated by Django 4.0.6 on 2022-07-27 22:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shosho', '0002_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='author_field',
            new_name='author',
        ),
    ]
