# Generated by Django 4.0.6 on 2022-08-03 16:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shosho', '0015_rename_receriver_threadmodel_receiver'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='thread',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='shosho.threadmodel'),
        ),
    ]
