# Generated by Django 4.0.6 on 2022-08-04 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shosho', '0016_notification_thread'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='uploads/post_pic')),
            ],
        ),
        migrations.RemoveField(
            model_name='post',
            name='image',
        ),
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ManyToManyField(blank=True, to='shosho.image'),
        ),
    ]
